version: '2.1'

services:
  deps:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: frizzlywitch/pycon2018_skill

  base:
    build: .

    command: "true" # чтобы этот сервис сразу завершил работу

    volumes:
      - ./seabattle:/skill/seabattle

  app:
    extends: base

    command: ""

  tests:
    extends: base

    command: "py.test -s /skill/tests"

    volumes:
      - ./tests:/skill/tests
